services:
  prowlarr:
    image: linuxserver/prowlarr:${VERSION}
    container_name: "prowlarr"

    restart: unless-stopped

    networks:
      - internet

    environment:
      PUID: ${UID}
      PGID: ${GID}

    volumes:
      - ${CONFIG_DIR}:/config

      - /etc/localtime:/etc/localtime:ro

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: "flaresolverr"

    restart: unless-stopped

    networks:
      - internet

    environment:
      LOG_LEVEL: info

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
