services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: "vaultwarden"

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    networks:
      - vaultwarden
      - internet

    volumes:
      - data:/data/

    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}

  db:
    image: postgres:16
    container_name: "vaultwarden-db"

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    networks:
      - vaultwarden

    volumes:
      - db-data:/var/lib/postgresql/data
      - db-backups:/backups

    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'pg_dump -U ${DB_USER} -d ${DB_NAME} > /backups/dump.sql'

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      start_period: 30s
    
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  vaultwarden:
  
  internet:
    external: true
    name: internet

volumes:
  data:
    name: vaultwarden-data

  db-data:
  db-backups:
    name: vaultwarden-db-backups