services:
  watchtower:
    image: containrrr/watchtower
    container_name: "watchtower"

    restart: unless-stopped

    environment:
      WATCHTOWER_CLEANUP: true
      WATCHTOWER_SCHEDULE: "0 0 5 * * 1"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro