{...}: {
  imports = [
    ./searx.nix
    ./nginx.nix
    ./radicale.nix
    ./miniflux.nix
    ./vaultwarden.nix
    ./invidious.nix
    ./syncthing.nix
    ./openssh.nix
    ./fail2ban.nix
    ./dnsmasq.nix
    ./samba
    ./gamemode.nix
    ./sunshine.nix
    ./gvfs.nix
    ./motd.nix
    ./kdeconnect.nix
    ./autoupgrade.nix
    ./caddy.nix
    ./qbittorrent.nix
    ./radarr.nix
    ./sonarr.nix
    ./prowlarr.nix
    ./jellyfin.nix
    ./ntfy.nix
    ./immich.nix
    ./uptime-kuma.nix
    ./unifi.nix
    ./homeassistant.nix
    ./mail-server.nix
    ./traccar.nix
    ./atuin.nix
    ./restic
    ./adguard.nix
    ./jellyseerr.nix
    ./free-epic-games.nix
    ./twitch-miner
    ./bazarr.nix
    ./mealie.nix
    ./soulseek.nix
    ./lidarr.nix
    ./recyclarr.nix
    ./rust-desk.nix
    ./forgejo.nix
    ./grafana.nix
    ./glance.nix
  ];
}
