services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: "portainer"

    restart: unless-stopped

    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - intranet

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  data:

networks:
  intranet:
    external: true
    name: intranet