name: Update flake lock file
on:
  schedule:
    - cron: "0 4 * * 6"
  workflow_dispatch:
jobs:
  update:
    name: Update flake inputs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v25

      - run: nix flake update --commit-lock-file --recreate-lock-file

      - uses: peter-evans/create-pull-request@v6
        with:
          branch: bot/update
          delete-branch: true
          title: Update flake inputs
