services:
  prowlarr:
    image: linuxserver/prowlarr:${VERSION}
    container_name: "prowlarr"

    restart: unless-stopped

    network_mode: "container:${VPN_CONTAINER_NAME}"

    environment:
      PUID: ${UID}
      PGID: ${GID}

    volumes:
      - ${CONFIG_DIR}:/config

      - /etc/localtime:/etc/localtime:ro
