services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:${VERSION}
    container_name: "homeassistant"

    restart: unless-stopped

    networks:
      - intranet

    hostname: ${HOSTNAME}

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    volumes:
      - ${CONFIG_DIR}:/config
      - /etc/localtime:/etc/localtime:ro

networks:
  intranet:
    external: true
    name: ${INTERNAL_NETWORK_NAME}
