services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: "searxng"

    restart: unless-stopped

    networks:
      - searxng
      - internet

    volumes:
      - ${CONFIG_DIR}:/etc/searxng:rw

    environment:
      SEARXNG_BASE_URL: ${BASE_URL}

    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
    external: false

  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
