services:
  dozzle:
    image: amir20/dozzle:${VERSION}
    container_name: "dozzle"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - intranet

networks:
  intranet:
    external: true
    name: intranet