services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION}
    container_name: "uptime-kuma"

    restart: unless-stopped

    volumes:
      - data:/app/data
    
    networks:
      - intranet

    labels:
      - com.centurylinklabs.watchtower.enable = false

volumes:
  data:
    name: uptime-kuma-data

networks:
  intranet:
    external: true
    name: intranet