services:
  uptime-kuma:
    image: louislam/uptime-kuma:${VERSION}
    container_name: "uptime-kuma"

    restart: unless-stopped

    volumes:
      - data:/app/data
        # - /etc/localtime:/etc/localtime:ro
    
    networks:
      - intranet

volumes:
  data:
    name: uptime-kuma-data

networks:
  intranet:
    external: true
    name: intranet
