services:
  sonarr:
    image: linuxserver/sonarr:${VERSION}
    container_name: "sonarr"

    restart: unless-stopped

    networks:
      - internet

    environment:
      PUID: ${UID}
      PGID: ${GID}

    volumes:
      - ${CONFIG_DIR}:/config
      - ${SCRIPTS_DIR}:/scripts
      - ${TV_DIR}:/tv
      - ${DOWNLOAD_DIR}:/downloads/

      - /etc/localtime:/etc/localtime:ro

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
