services:
  radarr:
    image: linuxserver/radarr:${VERSION}
    container_name: "radarr"

    restart: unless-stopped

    networks:
      - internet

    environment:
      PUID: ${UID}
      PGID: ${GID}

    volumes:
      - ${CONFIG_DIR}:/config
      - ${SCRIPTS_DIR}:/scripts
      - ${MOVIE_DIR}:/movies
      - ${DOWNLOAD_DIR}:/downloads/

      - /etc/localtime:/etc/localtime:ro

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
