services:
  bazarr:
    image: linuxserver/bazarr:${VERSION}
    container_name: "bazarr"

    restart: unless-stopped

    networks:
      - internet

    environment:
      PUID: ${UID}
      PGID: ${GID}

      PORT: ${PORT}

    volumes:
      - ${CONFIG_DIR}:/config
      - ${MOVIE_DIR}:/movies
      - ${TV_DIR}:/tv

      - /etc/localtime:/etc/localtime:ro

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
