services:
  caddy:
    image: caddy:2-alpine
    container_name: "caddy"

    restart: unless-stopped

    environment:
      UID: 1000
      GID: 1000

    networks:
      - internet

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-site:/srv
      - caddy-data:/data
      - caddy-config:/config

networks:
  internet:
    name: internet

volumes:
  caddy-site:
  caddy-data:
  caddy-config: