services:
  caddy:
    image: caddy:2-alpine
    container_name: "caddy"

    restart: unless-stopped

    environment:
      UID: 1000
      GID: 1000

    networks:
      - internet

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/lib/letsencrypt/certs:/data/caddy/certificates
      - caddy-site:/srv
      - caddy-data:/data
      - caddy-config:/config

networks:
  internet:
    name: internet

volumes:
  caddy-site:
  caddy-data:
  caddy-config: