services:
  miniflux:
    image: miniflux/miniflux:${VERSION}
    container_name: "miniflux"

    depends_on:
      db:
        condition: service_healthy

    environment:
      DATABASE_URL: postgres://${DB_USERNAME}:${DB_PASSWORD}@db/${DB_NAME}?sslmode=disable
      RUN_MIGRATIONS: 1
      CREATE_ADMIN: 1
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    networks:
      - intranet
      - internet
      - miniflux

  db:
    image: postgres:15
    container_name: "miniflux-db"

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - db-data:/var/lib/postgresql/data
      - db-backups:/backups/

    labels:
      - docker-volume-backup.archive-pre=/bin/sh -c 'pg_dump -U ${DB_USERNAME} -d ${DB_NAME} > /backups/dump.sql'

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      start_period: 30s

    networks:
      - miniflux

volumes:
  db-data:
  db-backups:
    name: miniflux-db-backups

networks:
  intranet:
    external: true
    name: intranet

  internet:
    external: true
    name: internet

  miniflux: