services:
  epicgames-freegames-node:
    image: ghcr.io/claabs/epicgames-freegames-node:latest
    container_name: "free-epic-games"

    restart: unless-stopped

    networks:
      - internet

    env_file: ${SECRETS_FILE}

    environment:
      RUN_ON_STARTUP: true
      BASE_URL: ${EXTERNAL_DOMAIN}
      EMAIL: ${EG_EMAIL}
      SMTP_PORT: 465
      SMTP_SECURE: true

    volumes:
      - ${CONFIG_DIR}:/usr/app/config
      - /etc/localtime:/etc/localtime:ro

    deploy:
      resources:
        limits:
          memory: 2g

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
