services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:${VERSION}
    container_name: "mail"

    restart: unless-stopped

    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: "mail.${BASE_DOMAIN}"

    environment:
      ENABLE_UPDATE_CHECK: 1
      UPDATE_CHECK_INTERVAL: 1d

      LOG_LEVEL: info

      POSTMASTER_ADDRESS: "postmaster@${BASE_DOMAIN}"
      SPOOF_PROTECTION: 1

      PERMIT_DOCKER: none

      ENABLE_SRS: 0
      ENABLE_OPENDKIM: 1
      ENABLE_OPENDMARC: 1
      ENABLE_POLICYD_SPF: 1
      ENABLE_POP3: 0
      ENABLE_IMAP: 1
      ENABLE_CLAMAV: 0
      ENABLE_RSPAMD: 0
      ENABLE_AMAVIS: 1
      ENABLE_SPAMASSASSIN: 0

      ENABLE_QUOTAS: 0

      ENABLE_FAIL2BAN: 1
      FAIL2BAN_BLOCKTYPE: drop

      ENABLE_MANAGESIEVE: 1

      DEFAULT_RELAY_HOST: "[in-v3.mailjet.com]:587"
      RELAY_USER: ${SMTP_RELAY_USER}
      RELAY_PASSWORD: ${SMTP_RELAY_PASSWORD}

      SSL_TYPE: letsencrypt

    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)

    volumes:
      - /var/lib/dms/data/:/var/mail/
      - /var/lib/dms/state/:/var/mail-state/
      - /var/lib/dms/logs/:/var/log/mail/
      - /var/lib/dms/config/:/tmp/docker-mailserver/

      - /var/lib/letsencrypt/certs/acme-v02.api.letsencrypt.org-directory/mail.guusvanmeerveld.dev/mail.guusvanmeerveld.dev.crt:/etc/letsencrypt/live/mail.guusvanmeerveld.dev/fullchain.pem
      - /var/lib/letsencrypt/certs/acme-v02.api.letsencrypt.org-directory/mail.guusvanmeerveld.dev/mail.guusvanmeerveld.dev.key:/etc/letsencrypt/live/mail.guusvanmeerveld.dev/privkey.pem

      - /etc/localtime:/etc/localtime:ro

    stop_grace_period: 1m

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    # Needed for Fail2Ban
    cap_add:
      - NET_ADMIN

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
