services:
  miner:
    image: rdavidoff/twitch-channel-points-miner-v2
    container_name: "twitch-miner"

    restart: unless-stopped

    # stdin_open: true
    # tty: true
    # environment:
    #   - TERM=xterm-256color

    volumes:
      - ${DATA_DIR}/analytics:/usr/src/app/analytics
      - ${DATA_DIR}/cookies:/usr/src/app/cookies
      - ${DATA_DIR}/logs:/usr/src/app/logs
      - ${RUN_FILE}:/usr/src/app/run.py:ro

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
