services:
  host:
    image: drone/drone:${VERSION}
    container_name: "drone"

    restart: unless-stopped

    networks:
      - internet

    volumes:
      - ${DATA_DIR}:/data

    environment:
      DRONE_GITEA_SERVER: ${GITEA_EXTERNAL_DOMAIN}
      DRONE_GITEA_CLIENT_ID: ${GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${GITEA_CLIENT_SECRET}

      DRONE_RPC_SECRET: ${RPC_SECRET}

      DRONE_SERVER_HOST: ${EXTERNAL_DOMAIN}
      DRONE_SERVER_PROTO: "https"

      DRONE_USER_CREATE: "username:${ADMIN_USERNAME},admin:true"

networks:
  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
