services:
  app:
    image: ghcr.io/vogler/free-games-claimer
    container_name: "free-games-claimer"

    restart: never

    volumes:
      - data:/fgc/data

    stdin_open: true
    tty: true

    environment:
      SHOW: 0
      NOTIFY: ${NOTIFY}
      EG_EMAIL: ${EG_EMAIL}
      EG_PASSWORD: ${EG_PASSWORD}
      EG_OTPKEY: ${EG_OTPKEY}

volumes:
  data: