services:
  vaultwarden:
    image: vaultwarden/server:${VERSION}
    container_name: "vaultwarden"

    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    networks:
      - vaultwarden
      - internet

    volumes:
      - ${DATA_DIR}:/data/

    environment:
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SIGNUPS_ALLOWED: false

      DOMAIN: ${EXTERNAL_DOMAIN}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PORT: 587
      SMTP_SECURITY: starttls
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}

  db:
    image: postgres:16
    container_name: "vaultwarden-db"

    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

    networks:
      - vaultwarden

    volumes:
      - ${DB_DATA_DIR}:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 10s
      start_period: 30s

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

networks:
  vaultwarden:

  internet:
    external: true
    name: ${DEFAULT_NETWORK_NAME}
